# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nll_cpp <- function(mu, Lambda, y, M) {
    .Call(`_FEShR_nll_cpp`, mu, Lambda, y, M)
}

ebmle_cpp_deriv <- function(mu, Lambda, y, M) {
    .Call(`_FEShR_ebmle_cpp_deriv`, mu, Lambda, y, M)
}

oracle_loss_cpp <- function(thetas, mu, Lambda, y, M) {
    .Call(`_FEShR_oracle_loss_cpp`, thetas, mu, Lambda, y, M)
}

oracle_cpp_deriv <- function(thetas, mu, Lambda, y, M) {
    .Call(`_FEShR_oracle_cpp_deriv`, thetas, mu, Lambda, y, M)
}

URE_cpp <- function(mu, Lambda, y, M) {
    .Call(`_FEShR_URE_cpp`, mu, Lambda, y, M)
}

URE_cpp_deriv <- function(mu, Lambda, y, M) {
    .Call(`_FEShR_URE_cpp_deriv`, mu, Lambda, y, M)
}

