# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_thetahat <- function(mu, Lambda, y, M) {
    .Call(`_FEShR_get_thetahat`, mu, Lambda, y, M)
}

get_Dmat_dvec <- function(Lambda, y, M) {
    .Call(`_FEShR_get_Dmat_dvec`, Lambda, y, M)
}

nll <- function(mu, Lambda, y, M) {
    .Call(`_FEShR_nll`, mu, Lambda, y, M)
}

nll_deriv <- function(mu, Lambda, y, M) {
    .Call(`_FEShR_nll_deriv`, mu, Lambda, y, M)
}

opt_mu_Lambda_nll <- function(Lambda, y, M) {
    .Call(`_FEShR_opt_mu_Lambda_nll`, Lambda, y, M)
}

opt_mu_Lambda_ol <- function(thetas, Lambda, y, M) {
    .Call(`_FEShR_opt_mu_Lambda_ol`, thetas, Lambda, y, M)
}

oracle_loss_cpp <- function(thetas, mu, Lambda, y, M) {
    .Call(`_FEShR_oracle_loss_cpp`, thetas, mu, Lambda, y, M)
}

oracle_cpp_deriv <- function(thetas, mu, Lambda, y, M) {
    .Call(`_FEShR_oracle_cpp_deriv`, thetas, mu, Lambda, y, M)
}

URE <- function(mu, Lambda, y, M) {
    .Call(`_FEShR_URE`, mu, Lambda, y, M)
}

URE_deriv <- function(mu, Lambda, y, M) {
    .Call(`_FEShR_URE_deriv`, mu, Lambda, y, M)
}

