# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_thetahat <- function(mu, Lambda, y, M, missing_cells, O) {
    .Call(`_FEShR_get_thetahat`, mu, Lambda, y, M, missing_cells, O)
}

nll <- function(mu, Lambda, y, M, missing_cells, O) {
    .Call(`_FEShR_nll`, mu, Lambda, y, M, missing_cells, O)
}

nll_deriv <- function(mu, Lambda, y, M, missing_cells, O) {
    .Call(`_FEShR_nll_deriv`, mu, Lambda, y, M, missing_cells, O)
}

gam_to_mu <- function(gam_opt, Z, T) {
    .Call(`_FEShR_gam_to_mu`, gam_opt, Z, T)
}

get_Dmat_dvec <- function(Lambda, y, M, W, missing_cells, O, Z) {
    .Call(`_FEShR_get_Dmat_dvec`, Lambda, y, M, W, missing_cells, O, Z)
}

opt_mu_Lambda_nll <- function(Lambda, y, M, missing_cells, O, Z) {
    .Call(`_FEShR_opt_mu_Lambda_nll`, Lambda, y, M, missing_cells, O, Z)
}

opt_mu_Lambda_ol <- function(thetas, Lambda, y, M, W, missing_cells, O, Z) {
    .Call(`_FEShR_opt_mu_Lambda_ol`, thetas, Lambda, y, M, W, missing_cells, O, Z)
}

oracle_loss <- function(thetas, mu, Lambda, y, M, W, missing_cells, O) {
    .Call(`_FEShR_oracle_loss`, thetas, mu, Lambda, y, M, W, missing_cells, O)
}

oracle_deriv <- function(thetas, mu, Lambda, y, M, W, missing_cells, O) {
    .Call(`_FEShR_oracle_deriv`, thetas, mu, Lambda, y, M, W, missing_cells, O)
}

opt_LamTmT_Lambda <- function(Lambda, y, M, missing_cells, O) {
    .Call(`_FEShR_opt_LamTmT_Lambda`, Lambda, y, M, missing_cells, O)
}

UPE <- function(Lambda, y, M, missing_cells, O, bounds) {
    .Call(`_FEShR_UPE`, Lambda, y, M, missing_cells, O, bounds)
}

get_thetahat_fc <- function(LamTmT, Lambda, y, M, missing_cells, O) {
    .Call(`_FEShR_get_thetahat_fc`, LamTmT, Lambda, y, M, missing_cells, O)
}

URE <- function(mu, Lambda, y, M, W, missing_cells, O) {
    .Call(`_FEShR_URE`, mu, Lambda, y, M, W, missing_cells, O)
}

URE_deriv <- function(mu, Lambda, y, M, W, missing_cells, O) {
    .Call(`_FEShR_URE_deriv`, mu, Lambda, y, M, W, missing_cells, O)
}

